# Generated by Django 2.1.5 on 2020-03-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('oper', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='action_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('trans_code', models.CharField(blank=True, max_length=64)),
                ('trans_err', models.CharField(blank=True, max_length=512)),
                ('problem_info', models.CharField(blank=True, max_length=3000)),
                ('problem_answer', models.CharField(blank=True, max_length=3000)),
                ('problem_answer_txt', models.CharField(blank=True, max_length=3000)),
                ('bank_id', models.CharField(blank=True, max_length=32, null=True)),
                ('bank_oper', models.CharField(blank=True, max_length=32, null=True)),
                ('problem_source', models.CharField(blank=True, max_length=32, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('input_oper', models.CharField(blank=True, max_length=64, null=True)),
                ('assign_oper', models.CharField(blank=True, max_length=64, null=True)),
                ('answer_oper', models.CharField(blank=True, max_length=64, null=True)),
                ('update_oper', models.CharField(blank=True, max_length=64, null=True)),
                ('update_chk_oper', models.CharField(blank=True, max_length=64, null=True)),
                ('info_check_flag', models.IntegerField()),
                ('info_check_update', models.IntegerField()),
                ('count_search', models.IntegerField(null=True)),
                ('count_chick', models.IntegerField(null=True)),
                ('comments_update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info_channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('update_oper', models.CharField(max_length=64)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='info_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.IntegerField(db_index=True, null=True)),
                ('stat_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='t_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search_problem.info_channel'),
        ),
        migrations.AddField(
            model_name='info',
            name='t_comments',
            field=models.ManyToManyField(blank=True, to='search_problem.info_comments'),
        ),
        migrations.AddField(
            model_name='info',
            name='t_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search_problem.info_stat'),
        ),
        migrations.AddField(
            model_name='info',
            name='t_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search_problem.info_type'),
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_problem.action_type'),
        ),
    ]
