# Generated by Django 2.1.5 on 2020-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
