# Generated by Django 2.1.5 on 2020-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_problem', '0002_auto_20200316_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='problem_answer',
            field=models.CharField(blank=True, max_length=6000),
        ),
    ]
