# Generated by Django 2.1.5 on 2020-04-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_zl_helloworld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yything',
        ),
        migrations.DeleteModel(
            name='yything_stat',
        ),
    ]
