# Generated by Django 2.1.5 on 2020-04-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trans_zl_helloworld', '0002_auto_20200402_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='yything',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('banknames', models.CharField(blank=True, max_length=128)),
                ('deal_person', models.CharField(blank=True, max_length=64)),
                ('support_org', models.CharField(blank=True, max_length=64)),
                ('stat', models.CharField(blank=True, max_length=16)),
                ('diffcult', models.CharField(blank=True, max_length=2048)),
                ('want_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yything_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.IntegerField(null=True)),
                ('stat_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='yything',
            name='t_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trans_zl_helloworld.yything_stat'),
        ),
    ]
