# Generated by Django 2.1.5 on 2020-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_zl_helloworld', '0004_auto_20200402_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yything',
            name='t_team',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.DeleteModel(
            name='enum_team',
        ),
    ]
