# Generated by Django 2.1.5 on 2020-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_zl_helloworld', '0006_auto_20200402_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='yything',
            name='genjin',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='yything',
            name='yanzheng',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
