# Generated by Django 2.1.5 on 2020-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_zl_helloworld', '0007_auto_20200402_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yything',
            name='support_org',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='yything',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
