# Generated by Django 2.1.5 on 2020-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('text', models.CharField(max_length=250, unique=True)),
                ('par', models.CharField(max_length=128, unique=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('url', 'api_id')},
        ),
    ]
