# Generated by Django 2.1.5 on 2020-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='dev_oper',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='par',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
