# Generated by Django 2.1.5 on 2019-11-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='file_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
