# Generated by Django 2.1.5 on 2019-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_file', '0005_auto_20191120_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='file_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('file_name', 'file_path')},
        ),
    ]
