# Generated by Django 2.1.5 on 2020-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_i_user_group_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_config_v1',
            name='app_bank',
            field=models.ManyToManyField(blank=True, to='cmdb.i_bank'),
        ),
    ]
