# Generated by Django 2.1.5 on 2020-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20200319_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='qq_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
