"""
Django settings for info_server project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lu*nuaa2(@wtr2yu0i=#)e8v0=b^rou(7+l^1sgexhqxi4uc4u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']
X_FRAME_OPTIONS = 'ALLOWALL'


# Session的cookie失效日期（秒）（默认）
SESSION_COOKIE_AGE = 43200
#SESSION_COOKIE_AGE = 60
SESSION_SAVE_EVERY_REQUEST = True



# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cmdb',
    'info',
    'myview',
    'trans_dlzf',
    'rjxf_server',
    'trans_jrick',
    'trans_yh',
    'trans_dlwl',
    'trans_fxq_report',
    'chkpcl_server',
    'monitor_wx_zfb',
    'monitor_wx_zfb_DAY',
    'monitor_wx_zfb_2',
    'trans_bwpt',
    'rota_day',
    'monitor_nzjs',
    'cloud_file',
    'auth_control',
    'data_control',
    'chkpcl_V2',
    'monitor_xysj_nzjs',
    'monitor_nzjs_renhang',
    'monitor_nzjs_szk',
    'sjtq_cib',
    'data_api',
    'search_problem',
    'trans_zl_helloworld',
    'topfe_reportform',
    'qq_data',
    'rate_system',
]
import sys
sys.path.insert(0,os.path.join(BASE_DIR,'server_trans'))
sys.path.insert(0,os.path.join(BASE_DIR,'server_aiops'))
sys.path.insert(0,os.path.join(BASE_DIR,'server_monitor'))
sys.path.insert(0,os.path.join(BASE_DIR,'server_sjtq'))
sys.path.insert(0,os.path.join(BASE_DIR,'server_basic'))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'info_server.urls'
LOGIN_URL = '/user/login.html'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'info_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'insp_ap',
        'USER': 'root',
        'PASSWORD': 'Cibwh1685/',
        'HOST': '163.1.6.40',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "/home/insp_ap/kunpeng/info_server/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "/var/www")
