# Generated by Django 2.1.5 on 2019-08-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dlwl_trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_date', models.DateField(db_index=True)),
                ('bank_id', models.CharField(max_length=32)),
                ('bank_name', models.CharField(db_index=True, max_length=128)),
                ('zfjg_name', models.CharField(db_index=True, max_length=256)),
                ('tran_tot', models.CharField(max_length=32)),
                ('tran_tot_amt', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tbl_dlwl_trans',
            unique_together={('settle_date', 'bank_name', 'zfjg_name')},
        ),
    ]
