# Generated by Django 2.1.5 on 2019-08-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_dlwl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_dlwl_trans',
            new_name='chnltrans',
        ),
    ]
