# Generated by Django 2.1.5 on 2019-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=30)),
                ('html_id', models.CharField(max_length=30)),
                ('html_title', models.CharField(max_length=128)),
                ('browser_name', models.CharField(max_length=64)),
                ('connect_type', models.CharField(max_length=64)),
            ],
        ),
    ]
