# Generated by Django 2.1.5 on 2019-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rjxf_id', models.CharField(max_length=64)),
                ('rjxf_type', models.CharField(max_length=4)),
                ('rjxf_txt', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.CharField(max_length=64)),
            ],
        ),
    ]
