# Generated by Django 2.1.5 on 2019-07-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='rjxf_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
