# Generated by Django 2.1.5 on 2019-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0002_flow_rjxf_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='rjxf_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
