# Generated by Django 2.1.5 on 2019-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0003_auto_20190723_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='rjxf_stat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
