# Generated by Django 2.1.5 on 2019-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0004_flow_rjxf_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_ch', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
