# Generated by Django 2.1.5 on 2019-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0005_file_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftp_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_id', models.CharField(max_length=64, unique=True)),
                ('ftp_pwd', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
