# Generated by Django 2.1.5 on 2019-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0006_ftp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftp_path',
            name='ftp_pwd',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
