# Generated by Django 2.1.5 on 2019-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0007_auto_20191015_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='rjxf_num_count',
            field=models.IntegerField(null=True),
        ),
    ]
