# Generated by Django 2.1.5 on 2019-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0008_flow_rjxf_num_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='make_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='update_oper',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
