# Generated by Django 2.1.5 on 2019-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0009_auto_20191101_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='make_oper',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
