# Generated by Django 2.1.5 on 2019-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0010_flow_make_oper'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rjxf_id', models.CharField(max_length=64, unique=True)),
                ('rjxf_type', models.CharField(max_length=4)),
                ('rjxf_txt', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.CharField(max_length=64)),
                ('rjxf_run_date', models.DateTimeField(blank=True, null=True)),
                ('rjxf_stat', models.CharField(blank=True, max_length=64, null=True)),
                ('rjxf_num_count', models.IntegerField(null=True)),
                ('make_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('make_oper', models.CharField(max_length=64, null=True)),
                ('update_oper', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
