# Generated by Django 2.1.5 on 2019-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0011_flow2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow2',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='flow2',
            name='rjxf_txt',
        ),
        migrations.AlterField(
            model_name='flow2',
            name='file_size',
            field=models.CharField(max_length=128),
        ),
    ]
