# Generated by Django 2.1.5 on 2019-12-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0012_auto_20191207_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flow2',
        ),
    ]
