# Generated by Django 2.1.5 on 2019-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0013_delete_flow2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='chk_stat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
