# Generated by Django 2.1.5 on 2020-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjxf_server', '0014_flow_chk_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='itsm_no',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='make_chk_oper',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
