# Generated by Django 2.1.5 on 2019-10-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monitor_trans_flow',
        ),
    ]
