# Generated by Django 2.1.5 on 2019-10-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0003_auto_20191009_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trans_flow',
        ),
    ]
