# Generated by Django 2.1.5 on 2019-10-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0011_auto_20191010_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trans_flow',
        ),
    ]
