# Generated by Django 2.1.5 on 2019-10-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0013_auto_20191010_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trans_flows',
            new_name='trans_flow',
        ),
    ]
