# Generated by Django 2.1.5 on 2019-10-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0014_auto_20191010_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trans_flow',
        ),
    ]
