# Generated by Django 2.1.5 on 2019-10-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0016_auto_20191010_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trans_flow',
        ),
    ]
