# Generated by Django 2.1.5 on 2019-10-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0018_auto_20191010_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trans_flow',
        ),
    ]
