# Generated by Django 2.1.5 on 2019-11-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_wx_zfb', '0021_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
