# Generated by Django 2.1.5 on 2020-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('oper', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2048)),
            ],
        ),
    ]
