# Generated by Django 2.1.5 on 2020-03-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qq_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('group', 'date', 'oper')},
        ),
    ]
